packages:
  - "apps/*"
  - "packages/*"
  - "exporters/*"

onlyBuiltDependencies:
  - esbuild
  - protobufjs
  - sharp
  - tesseract.js

allowBuilds:
  esbuild: true
  protobufjs: true
  sharp: true
  tesseract.js: true
