import "./commands/asset.js";
import "./commands/document.js";
import "./commands/entity3d.js";
import "./commands/lighting.js";
import "./commands/node.js";
import "./commands/page.js";
import "./commands/reference.js";
import "./commands/scene3d.js";
import "./commands/timeline.js";
