import {
  CURRENT_MIGRATION_VERSION,
  CURRENT_SCHEMA_VERSION,
  type CanonicalDesignDocument,
  type DesignNode,
  type TextStyle,
} from "@aevum/document-model";
import type { ProjectMetadata } from "@aevum/project-store";

const NOW = "2026-08-13T00:00:00.000Z";
const id = {
  workspace: "workspace_10000000-0000-4000-8000-000000000001",
  project: "project_10000000-0000-4000-8000-000000000002",
  doc: "doc_10000000-0000-4000-8000-000000000003",
  viewportDesktop: "viewport_10000000-0000-4000-8000-000000000004",
  viewportTablet: "viewport_10000000-0000-4000-8000-000000000005",
  viewportMobile: "viewport_10000000-0000-4000-8000-000000000006",
  page: "page_10000000-0000-4000-8000-000000000007",
  hero: "frame_10000000-0000-4000-8000-000000000008",
  eyebrow: "text_10000000-0000-4000-8000-000000000009",
  heading: "text_10000000-0000-4000-8000-000000000010",
  body: "text_10000000-0000-4000-8000-000000000011",
  accent: "shape_10000000-0000-4000-8000-000000000012",
  card: "frame_10000000-0000-4000-8000-000000000013",
  cardTitle: "text_10000000-0000-4000-8000-000000000014",
  font: "asset_10000000-0000-4000-8000-000000000015",
  timeline: "timeline_10000000-0000-4000-8000-000000000016",
  track: "track_10000000-0000-4000-8000-000000000017",
  k1: "keyframe_10000000-0000-4000-8000-000000000018",
  k2: "keyframe_10000000-0000-4000-8000-000000000019",
  scene: "scene_10000000-0000-4000-8000-000000000020",
  mesh: "mesh_10000000-0000-4000-8000-000000000021",
  modelAsset: "asset_10000000-0000-4000-8000-000000000022",
  material: "material_10000000-0000-4000-8000-000000000023",
  camera: "camera_10000000-0000-4000-8000-000000000024",
  light: "light_10000000-0000-4000-8000-000000000025",
  shot: "shot_10000000-0000-4000-8000-000000000026",
  sequence: "sequence_10000000-0000-4000-8000-000000000027",
} as const;

const px = (value: number) => ({ value, unit: "PX" as const, mode: "FIXED" as const });
const transform = (x = 0, y = 0, opacity = 1) => ({
  position: { x, y, z: 0 },
  rotation: { x: 0, y: 0, z: 0 },
  scale: { x: 1, y: 1, z: 1 },
  skew: { x: 0, y: 0 },
  anchor: { x: 0, y: 0 },
  pivot: { x: 0, y: 0, z: 0 },
  opacity,
  clipping: false,
  maskIds: [],
  coordinateSpace: "LOCAL" as const,
});
const base = (nodeId: string, name: string, parentId: string | null, x = 0, y = 0) => ({
  id: nodeId,
  name,
  parentId,
  childIds: [] as string[],
  visible: true,
  locked: false,
  transform: transform(x, y),
  sourceLinks: [],
  metadata: { tags: ["studio"], customData: {} as Record<string, unknown> },
});
const style = (size: number, weight: number): TextStyle => ({
  fontAssetId: id.font,
  fontFamily: "Basic",
  fallbackFamilies: ["Arial", "sans-serif"],
  // No real fidelity measurement (rankFontCandidates against a rendered reference) has ever run
  // for this fixture text, so UNKNOWN is the honest status -- not a claimed EXACT match.
  fontMatchStatus: "UNKNOWN",
  size: px(size),
  lineHeight: { multiplier: 1.08 },
  letterSpacing: px(0),
  weight,
  style: "NORMAL",
  variableAxes: { wght: weight },
  openTypeFeatures: { liga: true },
});
const textNode = (
  nodeId: string,
  name: string,
  parentId: string,
  content: string,
  x: number,
  y: number,
  textStyle: TextStyle,
): DesignNode => ({
  ...base(nodeId, name, parentId, x, y),
  type: "TEXT",
  content,
  runs: [{ start: 0, end: content.length, style: textStyle }],
  paragraphStyle: {
    alignment: "LEFT",
    verticalAlignment: "TOP",
    direction: "LTR",
    paragraphSpacingBefore: px(0),
    paragraphSpacingAfter: px(0),
    firstLineIndent: px(0),
    hangingIndent: px(0),
  },
  metadata: { tags: ["studio"], customData: { "aevum.studio.color": colorFor(textStyle.weight) } },
});
const colorFor = (weight: number): string => (weight >= 700 ? "#f4f5f0" : "#a9b0ad");

export function createStudioProjectFixture(): { project: ProjectMetadata; document: CanonicalDesignDocument } {
  const page: DesignNode = {
    ...base(id.page, "Launch page", null),
    type: "PAGE",
    pageKind: "WEB",
    childIds: [id.hero],
  };
  const hero: DesignNode = {
    ...base(id.hero, "Hero", id.page),
    type: "FRAME",
    layout: { type: "ABSOLUTE" },
    dimensions: { width: px(1440), height: px(900) },
    childIds: [id.accent, id.eyebrow, id.heading, id.body, id.card],
    metadata: { tags: ["studio"], customData: { "aevum.studio.fill": "#101310" } },
  };
  const accent: DesignNode = {
    ...base(id.accent, "Signal", id.hero, 92, 116),
    type: "SHAPE",
    shapeType: "RECTANGLE",
    geometry: {},
    dimensions: { width: px(8), height: px(84) },
    metadata: { tags: ["studio"], customData: { "aevum.studio.fill": "#ef5a3c", "aevum.studio.radius": 4 } },
  };
  const eyebrow = textNode(id.eyebrow, "Eyebrow", id.hero, "MAXIMUM FIDELITY / 01", 124, 116, style(16, 600));
  const heading = textNode(
    id.heading,
    "Hero heading",
    id.hero,
    "Form follows\nintelligence.",
    124,
    176,
    style(86, 760),
  );
  heading.dimensions = { width: px(760), height: px(208) };
  heading.responsive = {
    breakpoints: {
      mobile: { transform: { position: { x: 40, y: 128, z: 0 } }, textStyle: { size: px(48) } },
    },
    reducedMotionOverride: { motion: { behavior: "REDUCE", durationScale: 0.2 } },
  };
  const body = textNode(
    id.body,
    "Introduction",
    id.hero,
    "A precise workspace for reconstructing, directing, and validating visual systems.",
    128,
    438,
    style(22, 400),
  );
  body.dimensions = { width: px(550), height: px(72) };
  const card: DesignNode = {
    ...base(id.card, "Stat card", id.hero, 950, 132),
    type: "FRAME",
    layout: { type: "ABSOLUTE" },
    dimensions: { width: px(360), height: px(580) },
    childIds: [id.cardTitle],
    transform: { ...transform(950, 132), rotation: { x: 0, y: 0, z: -3 } },
    metadata: { tags: ["studio"], customData: { "aevum.studio.fill": "#d9dfd2", "aevum.studio.radius": 6 } },
  };
  // Not a claimed fidelity score -- real ValidationRecords come from fidelity.measure (Block D8)
  // and are never fabricated demo copy.
  const cardTitle = textNode(id.cardTitle, "Card label", id.card, "PRECISION\nDESIGN", 42, 390, style(48, 760));
  cardTitle.metadata = { tags: ["studio"], customData: { "aevum.studio.color": "#151917" } };
  cardTitle.dimensions = { width: px(250), height: px(120) };
  const scene: DesignNode = {
    ...base(id.scene, "Product scene", null),
    type: "SCENE_3D",
    childIds: [id.mesh],
    activeCameraId: id.camera,
    lightIds: [id.light],
    coordinateSystem: {
      handedness: "RIGHT_HANDED",
      upAxis: "Y",
      forwardAxis: "NEGATIVE_Z",
      unit: "M",
      rotationUnit: "RADIANS",
      quaternionOrder: "XYZW",
      transformComposition: "TRS",
    },
  };
  const mesh: DesignNode = {
    ...base(id.mesh, "Reconstructed product", id.scene),
    type: "MESH_3D",
    geometryAssetId: id.modelAsset,
    geometry: {
      sourceAssetId: id.modelAsset,
      sourceMeshIndex: 0,
      sourcePrimitiveIndex: 0,
      primitiveMode: "TRIANGLES",
      vertexCount: 24,
      indexCount: 36,
      triangleCount: 12,
      attributes: [],
      normalAvailable: true,
      tangentAvailable: false,
      texCoordSets: 1,
      skinAttributes: false,
      morphTargetCount: 0,
      drawCallEstimate: 1,
    },
    materialIds: [id.material],
    topology: { vertices: 24, faces: 6, triangles: 12, manifold: true },
    castShadow: true,
    receiveShadow: true,
  };

  const document: CanonicalDesignDocument = {
    schemaVersion: CURRENT_SCHEMA_VERSION,
    migrationVersion: CURRENT_MIGRATION_VERSION,
    documentVersion: 1,
    parentVersionId: null,
    metadata: {
      id: id.doc,
      projectId: id.project,
      name: "AEVUM Launch System",
      createdAt: NOW,
      updatedAt: NOW,
      createdBy: { id: "studio-fixture", type: "SYSTEM", displayName: "AEVUM Studio" },
      updatedBy: { id: "studio-fixture", type: "SYSTEM", displayName: "AEVUM Studio" },
      version: 1,
      projectVersion: 1,
      tags: ["studio", "acceptance"],
      description: "Persisted Phase 23 Studio acceptance project.",
    },
    rootNodeIds: [id.page, id.scene],
    pages: [id.page],
    nodes: {
      [id.page]: page,
      [id.hero]: hero,
      [id.accent]: accent,
      [id.eyebrow]: eyebrow,
      [id.heading]: heading,
      [id.body]: body,
      [id.card]: card,
      [id.cardTitle]: cardTitle,
      [id.scene]: scene,
      [id.mesh]: mesh,
    },
    assets: {
      [id.font]: {
        id: id.font,
        type: "FONT",
        name: "Basic Regular",
        hash: `sha256:${"1".repeat(64)}`,
        source: { kind: "UPLOAD", uri: "/fonts/Basic-Regular.ttf" },
        mimeType: "font/ttf",
        byteSize: 1536,
        metadata: { family: "Basic", style: "Regular", weight: 400 },
      },
      [id.modelAsset]: {
        id: id.modelAsset,
        type: "GLB",
        name: "Reconstructed product",
        hash: `sha256:${"2".repeat(64)}`,
        source: { kind: "GENERATED", uri: "registered/studio-product.glb" },
        mimeType: "model/gltf-binary",
        byteSize: 4096,
        metadata: { meshes: 1, materials: 1 },
      },
    },
    components: {},
    tokens: {},
    typography: {},
    stateMachines: {},
    cameraPaths: {},
    environments: {},
    lightingRigs: {},
    lightingProfiles: {},
    reflectionProbes: {},
    lightingBakes: {},
    references: {},
    validations: {},
    exports: {},
    cameras: {
      [id.camera]: {
        id: id.camera,
        name: "Hero camera",
        projection: "PERSPECTIVE",
        transform: { ...transform(0, 1.6), position: { x: 4.2, y: 3.2, z: 5.4 } },
        focalLength: 50,
        sensor: { width: 36, height: 24, fit: "AUTO" },
        lensShift: { x: 0, y: 0 },
        roll: 0,
        anamorphicRatio: 1,
        nearClip: 0.1,
        farClip: 1000,
        depthOfField: { enabled: true, aperture: 2.8, focusDistance: 5, bladeCount: 6 },
        targetingMode: "LOOK_AT_POINT",
        target: { x: 0, y: 0, z: 0 },
        upVector: { x: 0, y: 1, z: 0 },
        framing: { safeArea: { x: 0.9, y: 0.9 }, guide: "RULE_OF_THIRDS" },
        metadata: {},
      },
    },
    lights: {
      [id.light]: {
        id: id.light,
        name: "Soft key",
        type: "AREA",
        transform: { ...transform(), position: { x: 3, y: 4, z: 2 } },
        color: { r: 1, g: 0.72, b: 0.62, a: 1, colorSpace: "SRGB" },
        intensity: 1200,
        temperatureKelvin: 5200,
        exposure: 0,
        castShadow: true,
        shape: "RECTANGLE",
        size: { width: 3, height: 3 },
        shadow: {
          enabled: true,
          mode: "DYNAMIC",
          mapSize: 2048,
          bias: -0.001,
          normalBias: 0.02,
          radius: 2,
          contact: true,
        },
        metadata: {},
      },
    },
    materials: {
      [id.material]: {
        id: id.material,
        name: "Brushed alloy",
        type: "PBR",
        pbr: {
          baseColor: { r: 0.76, g: 0.81, b: 0.77, a: 1, colorSpace: "SRGB" },
          roughness: 0.38,
          metalness: 0.28,
          opacity: 1,
        },
        textures: [],
        metadata: {},
      },
    },
    cinematicShots: {
      [id.shot]: {
        id: id.shot,
        name: "Hero reveal",
        cameraId: id.camera,
        startTime: 0,
        duration: 2,
        transitionIn: { type: "CUT", duration: 0, easing: { type: "LINEAR" } },
        composition: { subjectNodeId: id.mesh, guide: "RULE_OF_THIRDS", desiredCoverage: 0.62, safeMargin: 0.05 },
        metadata: {},
      },
    },
    cinematicSequences: {
      [id.sequence]: {
        id: id.sequence,
        version: "1.0.0",
        name: "Product reveal",
        sceneId: id.scene,
        shotIds: [id.shot],
        duration: 2,
        allowGaps: false,
        metadata: {},
      },
    },
    timelines: {
      [id.timeline]: {
        id: id.timeline,
        version: "1.0.0",
        name: "Hero entrance",
        type: "LOAD",
        duration: 2,
        frameRate: 60,
        timeScale: 1,
        loop: { enabled: false, count: 1, mode: "RESTART" },
        tracks: [
          {
            id: id.track,
            targetId: id.heading,
            property: "OPACITY",
            propertyPath: "transform.opacity",
            valueType: "NUMBER",
            muted: false,
            locked: false,
            layer: 0,
            keyframes: [
              { id: id.k1, time: 0, value: 0, easing: { type: "EASE_OUT" }, interpolation: "LINEAR", metadata: {} },
              { id: id.k2, time: 1.1, value: 1, easing: { type: "EASE_OUT" }, interpolation: "LINEAR", metadata: {} },
            ],
          },
        ],
        clips: [],
        markers: [],
        triggers: [],
        events: [],
        labels: {},
        metadata: {},
      },
    },
    settings: {
      qualityMode: "MAXIMUM_FIDELITY",
      defaultViewportId: id.viewportDesktop,
      viewports: {
        [id.viewportDesktop]: {
          id: id.viewportDesktop,
          name: "Desktop",
          width: 1440,
          height: 900,
          deviceScaleFactor: 1,
          orientation: "LANDSCAPE",
          category: "DESKTOP",
        },
        [id.viewportTablet]: {
          id: id.viewportTablet,
          name: "Tablet",
          width: 834,
          height: 1112,
          deviceScaleFactor: 1,
          orientation: "PORTRAIT",
          category: "TABLET",
        },
        [id.viewportMobile]: {
          id: id.viewportMobile,
          name: "Mobile",
          width: 390,
          height: 844,
          deviceScaleFactor: 1,
          orientation: "PORTRAIT",
          category: "MOBILE",
        },
      },
      defaultColorSpace: "SRGB",
      defaultUnit: "PX",
      frameRate: 60,
      deterministicSeed: 23,
      reducedMotion: "PRESERVE",
    },
  };
  return {
    project: {
      id: id.project,
      workspaceId: id.workspace,
      name: "AEVUM Launch System",
      description: "Phase 23 acceptance project",
      tags: ["studio"],
      createdAt: NOW,
      updatedAt: NOW,
    },
    document,
  };
}

export const studioFixtureIds = Object.freeze(id);
